import { ReactNode } from 'react'
import './globals.css'
import { Sora } from 'next/font/google'

const sora = Sora({ subsets: ['latin'] })
// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Inter. Simplifica a vida.',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={sora.className}>{children}</body>
    </html>
  )
}
